// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} cover
 * @returns {Promise<$models.Image[]> & { cancel(): void }}
 */
export function GetCover(cover) {
    let $resultPromise = /** @type {any} */($Call.ByID(2756693912, cover));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} header
 * @returns {Promise<$models.ApiGame[]> & { cancel(): void }}
 */
export function GetGames(header) {
    let $resultPromise = /** @type {any} */($Call.ByID(195213204, header));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.Image.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ApiGame.createFrom;
const $$createType3 = $Create.Array($$createType2);
