// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ApiGame {
    /**
     * Creates a new ApiGame instance.
     * @param {Partial<ApiGame>} [$$source = {}] - The source object to create the ApiGame.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("cover" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cover"] = 0;
        }
        if (!("Covers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Covers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiGame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApiGame}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Covers" in $$parsedSource) {
            $$parsedSource["Covers"] = $$createField4_0($$parsedSource["Covers"]);
        }
        return new ApiGame(/** @type {Partial<ApiGame>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
