// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} magnetLink
 * @returns {Promise<$models.AddMagnetResponse> & { cancel(): void }}
 */
export function AddTorrentByMagnet(magnetLink) {
    let $resultPromise = /** @type {any} */($Call.ByID(3871769746, magnetLink));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<$models.AvailableHost[]> & { cancel(): void }}
 */
export function AvailableHosts() {
    let $resultPromise = /** @type {any} */($Call.ByID(2761054400));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} magnetLink
 * @param {string} path
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DownloadByMagnet(magnetLink, path) {
    let $resultPromise = /** @type {any} */($Call.ByID(717111301, magnetLink, path));
    return $resultPromise;
}

/**
 * @param {string} link
 * @param {string} filePath
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DownloadDirectLink(link, filePath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1080804783, link, filePath));
    return $resultPromise;
}

/**
 * @param {$models.UnrestrictResponse[]} unrestrictResponses
 * @returns {Promise<number> & { cancel(): void }}
 */
export function GetDiskSizeOfAllLinks(unrestrictResponses) {
    let $resultPromise = /** @type {any} */($Call.ByID(994908471, unrestrictResponses));
    return $resultPromise;
}

/**
 * @returns {Promise<$models.DownloadProgress> & { cancel(): void }}
 */
export function GetDownloadProgress() {
    let $resultPromise = /** @type {any} */($Call.ByID(4165838017));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<$models.DownloadItem[]> & { cancel(): void }}
 */
export function GetDownloads() {
    let $resultPromise = /** @type {any} */($Call.ByID(4283940807));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<$models.Torrent[]> & { cancel(): void }}
 */
export function GetTorents() {
    let $resultPromise = /** @type {any} */($Call.ByID(4269175713));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType7($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} id
 * @returns {Promise<$models.Torrent> & { cancel(): void }}
 */
export function GetTorrentInfoById(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(2465184132, id));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType6($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<{ [_: string]: $models.TrafficInfo }> & { cancel(): void }}
 */
export function GetTraffic() {
    let $resultPromise = /** @type {any} */($Call.ByID(2804281747));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType9($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Returns some informations on the current user.
 * @returns {Promise<$models.RealDebridUser | null> & { cancel(): void }}
 */
export function GetUser() {
    let $resultPromise = /** @type {any} */($Call.ByID(1335467865));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType11($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SelectFiles This function is supposed to be called after AddTorrentByMagnet() or similar. Because Real debrid needs to know which files to torrent
 * @param {$models.Torrent} torrent
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SelectFiles(torrent) {
    let $resultPromise = /** @type {any} */($Call.ByID(3618906341, torrent));
    return $resultPromise;
}

/**
 * @param {string} link
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function UnrestrictCheck(link) {
    let $resultPromise = /** @type {any} */($Call.ByID(3637606915, link));
    return $resultPromise;
}

/**
 * @param {string} link
 * @returns {Promise<$models.UnrestrictResponse> & { cancel(): void }}
 */
export function UnrestrictLink(link) {
    let $resultPromise = /** @type {any} */($Call.ByID(4231798901, link));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType12($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.AddMagnetResponse.createFrom;
const $$createType1 = $models.AvailableHost.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DownloadProgress.createFrom;
const $$createType4 = $models.DownloadItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Torrent.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.TrafficInfo.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = $models.RealDebridUser.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.UnrestrictResponse.createFrom;
