// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Maintains state of torrent within a Client. Many methods should not be called before the info is
 * available, see .Info and .GotInfo.
 */
export class Torrent {
    /**
     * Creates a new Torrent instance.
     * @param {Partial<Torrent>} [$$source = {}] - The source object to create the Torrent.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Torrent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Torrent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Torrent(/** @type {Partial<Torrent>} */($$parsedSource));
    }
}
