// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("path_to_settings" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path_to_settings"] = "";
        }
        if (!("download_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_path"] = "";
        }
        if (!("use_real_debrid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["use_real_debrid"] = false;
        }
        if (!("game_sources" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["game_sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("game_sources" in $$parsedSource) {
            $$parsedSource["game_sources"] = $$createField3_0($$parsedSource["game_sources"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
