// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ApiGame {
    /**
     * Creates a new ApiGame instance.
     * @param {Partial<ApiGame>} [$$source = {}] - The source object to create the ApiGame.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("cover" in $$source)) {
            /**
             * @member
             * @type {Image}
             */
            this["cover"] = (new Image());
        }
        if (!("CoverURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CoverURL"] = "";
        }
        if (!("artworks" in $$source)) {
            /**
             * @member
             * @type {Image[]}
             */
            this["artworks"] = [];
        }
        if (!("ArtworkUrlList" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ArtworkUrlList"] = [];
        }
        if (!("screenshots" in $$source)) {
            /**
             * @member
             * @type {Image[]}
             */
            this["screenshots"] = [];
        }
        if (!("ScreenshotUrlList" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ScreenshotUrlList"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiGame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApiGame}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cover" in $$parsedSource) {
            $$parsedSource["cover"] = $$createField3_0($$parsedSource["cover"]);
        }
        if ("artworks" in $$parsedSource) {
            $$parsedSource["artworks"] = $$createField5_0($$parsedSource["artworks"]);
        }
        if ("ArtworkUrlList" in $$parsedSource) {
            $$parsedSource["ArtworkUrlList"] = $$createField6_0($$parsedSource["ArtworkUrlList"]);
        }
        if ("screenshots" in $$parsedSource) {
            $$parsedSource["screenshots"] = $$createField7_0($$parsedSource["screenshots"]);
        }
        if ("ScreenshotUrlList" in $$parsedSource) {
            $$parsedSource["ScreenshotUrlList"] = $$createField8_0($$parsedSource["ScreenshotUrlList"]);
        }
        return new ApiGame(/** @type {Partial<ApiGame>} */($$parsedSource));
    }
}

export class Image {
    /**
     * Creates a new Image instance.
     * @param {Partial<Image>} [$$source = {}] - The source object to create the Image.
     */
    constructor($$source = {}) {
        if (!("image_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Image instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Image}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Image(/** @type {Partial<Image>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Image.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
